import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import "@/styles/globals.css";

import { cn } from "@/lib/utils";
import { geistSans } from "@/lib/fonts";

import { PropsWithChildren } from "@/types";

import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn("font-geist", geistSans.variable)}>{children}</body>
      </html>
    </SessionProvider>
  );
}
